#!/usr/bin/env bash

# Bash strict mode
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

HERE="`dirname $0`"
VERSION="1.5.1"
COURSIER="$HERE/.coursier"
SCALAFMT="$HERE/.scalafmt-$VERSION"

if [ ! -x "$COURSIER" ]; then
  curl -L -o "$COURSIER" "https://github.com/coursier/coursier/raw/v1.0.3/coursier"
  chmod +x "$COURSIER"
fi

if [ ! -f "$SCALAFMT" ]; then
  "$COURSIER" bootstrap com.geirsson:scalafmt-cli_2.11:$VERSION --main org.scalafmt.cli.Cli -o "$SCALAFMT"
  chmod +x "$SCALAFMT"
fi

exec "$SCALAFMT" "$@" >/dev/null
