import scala.scalanative._
import scala.scalanative.native.Nat._

@native.extern
object dirent {
  type __u_char = native.CUnsignedChar
  type __u_short = native.CUnsignedShort
  type __u_int = native.CUnsignedInt
  type __u_long = native.CUnsignedLong
  type __int8_t = native.CSignedChar
  type __uint8_t = native.CUnsignedChar
  type __int16_t = native.CShort
  type __uint16_t = native.CUnsignedShort
  type __int32_t = native.CInt
  type __uint32_t = native.CUnsignedInt
  type __int64_t = native.CLong
  type __uint64_t = native.CUnsignedLong
  type __quad_t = native.CLong
  type __u_quad_t = native.CUnsignedLong
  type __dev_t = native.CUnsignedLong
  type __uid_t = native.CUnsignedInt
  type __gid_t = native.CUnsignedInt
  type __ino_t = native.CUnsignedLong
  type __ino64_t = native.CUnsignedLong
  type __mode_t = native.CUnsignedInt
  type __nlink_t = native.CUnsignedLong
  type __off_t = native.CLong
  type __off64_t = native.CLong
  type __pid_t = native.CInt
  type struct___fsid_t = native.CStruct1[native.CArray[native.CInt, _2]]
  type __fsid_t = struct___fsid_t
  type __clock_t = native.CLong
  type __rlim_t = native.CUnsignedLong
  type __rlim64_t = native.CUnsignedLong
  type __id_t = native.CUnsignedInt
  type __time_t = native.CLong
  type __useconds_t = native.CUnsignedInt
  type __suseconds_t = native.CLong
  type __daddr_t = native.CInt
  type __key_t = native.CInt
  type __clockid_t = native.CInt
  type __timer_t = native.Ptr[Byte]
  type __blksize_t = native.CLong
  type __blkcnt_t = native.CLong
  type __blkcnt64_t = native.CLong
  type __fsblkcnt_t = native.CUnsignedLong
  type __fsblkcnt64_t = native.CUnsignedLong
  type __fsfilcnt_t = native.CUnsignedLong
  type __fsfilcnt64_t = native.CUnsignedLong
  type __fsword_t = native.CLong
  type __ssize_t = native.CLong
  type __syscall_slong_t = native.CLong
  type __syscall_ulong_t = native.CUnsignedLong
  type __loff_t = __off64_t
  type __qaddr_t = native.Ptr[__quad_t]
  type __caddr_t = native.Ptr[native.CChar]
  type __intptr_t = native.CLong
  type __socklen_t = native.CUnsignedInt
  type struct_dirent = native.CStruct5[__ino_t,__off_t,native.CUnsignedShort,native.CUnsignedChar,native.CArray[native.CChar, Digit[_2, Digit[_5, _6]]]]
  val enum_DT_UNKNOWN = 0
  val enum_DT_FIFO = 1
  val enum_DT_CHR = 2
  val enum_DT_DIR = 3
  val enum_DT_BLK = 4
  val enum_DT_REG = 5
  val enum_DT_LNK = 6
  val enum_DT_SOCK = 7
  val enum_DT_WHT = 8
  type DIR = struct___dirstream
  def opendir(__name: native.Ptr[native.CChar]): native.Ptr[DIR] = native.extern
  def fdopendir(__fd: native.CInt): native.Ptr[DIR] = native.extern
  def closedir(__dirp: native.Ptr[DIR]): native.CInt = native.extern
  def readdir(__dirp: native.Ptr[DIR]): native.Ptr[struct_dirent] = native.extern
  def readdir_r(__dirp: native.Ptr[DIR], __entry: native.Ptr[struct_dirent], __result: native.Ptr[native.Ptr[struct_dirent]]): native.CInt = native.extern
  def rewinddir(__dirp: native.Ptr[DIR]): Unit = native.extern
  def seekdir(__dirp: native.Ptr[DIR], __pos: native.CLong): Unit = native.extern
  def telldir(__dirp: native.Ptr[DIR]): native.CLong = native.extern
  def dirfd(__dirp: native.Ptr[DIR]): native.CInt = native.extern
  type size_t = native.CUnsignedLong
  def scandir(__dir: native.Ptr[native.CChar], __namelist: native.Ptr[native.Ptr[native.Ptr[struct_dirent]]], __selector: native.CFunctionPtr1[native.CInt,native.Ptr[struct_dirent]], __cmp: native.CFunctionPtr2[native.CInt,native.Ptr[native.Ptr[struct_dirent]],native.Ptr[native.Ptr[struct_dirent]]]): native.CInt = native.extern
  def alphasort(__e1: native.Ptr[native.Ptr[struct_dirent]], __e2: native.Ptr[native.Ptr[struct_dirent]]): native.CInt = native.extern
  def getdirentries(__fd: native.CInt, __buf: native.Ptr[native.CChar], __nbytes: native.CSize, __basep: native.Ptr[__off_t]): __ssize_t = native.extern
}
