import scala.scalanative._

@native.link("uv")
@native.extern
object uv {
  type enum_uv_errno_t = native.CInt
  val enum_uv_errno_t_UV_E2BIG = 0
  val enum_uv_errno_t_UV_EACCES = 1
  val enum_uv_errno_t_UV_EADDRINUSE = 2
  val enum_uv_errno_t_UV_EADDRNOTAVAIL = 3
  val enum_uv_errno_t_UV_EAFNOSUPPORT = 4
  val enum_uv_errno_t_UV_EAGAIN = 5
  val enum_uv_errno_t_UV_EAI_ADDRFAMILY = 6
  val enum_uv_errno_t_UV_EAI_AGAIN = 7
  val enum_uv_errno_t_UV_EAI_BADFLAGS = 8
  val enum_uv_errno_t_UV_EAI_BADHINTS = 9
  val enum_uv_errno_t_UV_EAI_CANCELED = 10
  val enum_uv_errno_t_UV_EAI_FAIL = 11
  val enum_uv_errno_t_UV_EAI_FAMILY = 12
  val enum_uv_errno_t_UV_EAI_MEMORY = 13
  val enum_uv_errno_t_UV_EAI_NODATA = 14
  val enum_uv_errno_t_UV_EAI_NONAME = 15
  val enum_uv_errno_t_UV_EAI_OVERFLOW = 16
  val enum_uv_errno_t_UV_EAI_PROTOCOL = 17
  val enum_uv_errno_t_UV_EAI_SERVICE = 18
  val enum_uv_errno_t_UV_EAI_SOCKTYPE = 19
  val enum_uv_errno_t_UV_EALREADY = 20
  val enum_uv_errno_t_UV_EBADF = 21
  val enum_uv_errno_t_UV_EBUSY = 22
  val enum_uv_errno_t_UV_ECANCELED = 23
  val enum_uv_errno_t_UV_ECHARSET = 24
  val enum_uv_errno_t_UV_ECONNABORTED = 25
  val enum_uv_errno_t_UV_ECONNREFUSED = 26
  val enum_uv_errno_t_UV_ECONNRESET = 27
  val enum_uv_errno_t_UV_EDESTADDRREQ = 28
  val enum_uv_errno_t_UV_EEXIST = 29
  val enum_uv_errno_t_UV_EFAULT = 30
  val enum_uv_errno_t_UV_EFBIG = 31
  val enum_uv_errno_t_UV_EHOSTUNREACH = 32
  val enum_uv_errno_t_UV_EINTR = 33
  val enum_uv_errno_t_UV_EINVAL = 34
  val enum_uv_errno_t_UV_EIO = 35
  val enum_uv_errno_t_UV_EISCONN = 36
  val enum_uv_errno_t_UV_EISDIR = 37
  val enum_uv_errno_t_UV_ELOOP = 38
  val enum_uv_errno_t_UV_EMFILE = 39
  val enum_uv_errno_t_UV_EMSGSIZE = 40
  val enum_uv_errno_t_UV_ENAMETOOLONG = 41
  val enum_uv_errno_t_UV_ENETDOWN = 42
  val enum_uv_errno_t_UV_ENETUNREACH = 43
  val enum_uv_errno_t_UV_ENFILE = 44
  val enum_uv_errno_t_UV_ENOBUFS = 45
  val enum_uv_errno_t_UV_ENODEV = 46
  val enum_uv_errno_t_UV_ENOENT = 47
  val enum_uv_errno_t_UV_ENOMEM = 48
  val enum_uv_errno_t_UV_ENONET = 49
  val enum_uv_errno_t_UV_ENOPROTOOPT = 50
  val enum_uv_errno_t_UV_ENOSPC = 51
  val enum_uv_errno_t_UV_ENOSYS = 52
  val enum_uv_errno_t_UV_ENOTCONN = 53
  val enum_uv_errno_t_UV_ENOTDIR = 54
  val enum_uv_errno_t_UV_ENOTEMPTY = 55
  val enum_uv_errno_t_UV_ENOTSOCK = 56
  val enum_uv_errno_t_UV_ENOTSUP = 57
  val enum_uv_errno_t_UV_EPERM = 58
  val enum_uv_errno_t_UV_EPIPE = 59
  val enum_uv_errno_t_UV_EPROTO = 60
  val enum_uv_errno_t_UV_EPROTONOSUPPORT = 61
  val enum_uv_errno_t_UV_EPROTOTYPE = 62
  val enum_uv_errno_t_UV_ERANGE = 63
  val enum_uv_errno_t_UV_EROFS = 64
  val enum_uv_errno_t_UV_ESHUTDOWN = 65
  val enum_uv_errno_t_UV_ESPIPE = 66
  val enum_uv_errno_t_UV_ESRCH = 67
  val enum_uv_errno_t_UV_ETIMEDOUT = 68
  val enum_uv_errno_t_UV_ETXTBSY = 69
  val enum_uv_errno_t_UV_EXDEV = 70
  val enum_uv_errno_t_UV_UNKNOWN = 71
  val enum_uv_errno_t_UV_EOF = 72
  val enum_uv_errno_t_UV_ENXIO = 73
  val enum_uv_errno_t_UV_EMLINK = 74
  val enum_uv_errno_t_UV_EHOSTDOWN = 75
  val enum_uv_errno_t_UV_ERRNO_MAX = 76
  type uv_errno_t = enum_uv_errno_t
  type enum_uv_handle_type = native.CInt
  val enum_uv_handle_type_UV_UNKNOWN_HANDLE = 0
  val enum_uv_handle_type_UV_ASYNC = 1
  val enum_uv_handle_type_UV_CHECK = 2
  val enum_uv_handle_type_UV_FS_EVENT = 3
  val enum_uv_handle_type_UV_FS_POLL = 4
  val enum_uv_handle_type_UV_HANDLE = 5
  val enum_uv_handle_type_UV_IDLE = 6
  val enum_uv_handle_type_UV_NAMED_PIPE = 7
  val enum_uv_handle_type_UV_POLL = 8
  val enum_uv_handle_type_UV_PREPARE = 9
  val enum_uv_handle_type_UV_PROCESS = 10
  val enum_uv_handle_type_UV_STREAM = 11
  val enum_uv_handle_type_UV_TCP = 12
  val enum_uv_handle_type_UV_TIMER = 13
  val enum_uv_handle_type_UV_TTY = 14
  val enum_uv_handle_type_UV_UDP = 15
  val enum_uv_handle_type_UV_SIGNAL = 16
  val enum_uv_handle_type_UV_FILE = 17
  val enum_uv_handle_type_UV_HANDLE_TYPE_MAX = 18
  type uv_handle_type = enum_uv_handle_type
  type enum_uv_req_type = native.CInt
  val enum_uv_req_type_UV_UNKNOWN_REQ = 0
  val enum_uv_req_type_UV_REQ = 1
  val enum_uv_req_type_UV_CONNECT = 2
  val enum_uv_req_type_UV_WRITE = 3
  val enum_uv_req_type_UV_SHUTDOWN = 4
  val enum_uv_req_type_UV_UDP_SEND = 5
  val enum_uv_req_type_UV_FS = 6
  val enum_uv_req_type_UV_WORK = 7
  val enum_uv_req_type_UV_GETADDRINFO = 8
  val enum_uv_req_type_UV_GETNAMEINFO = 9
  val enum_uv_req_type_UV_REQ_TYPE_PRIVATE = 10
  val enum_uv_req_type_UV_REQ_TYPE_MAX = 11
  type uv_req_type = enum_uv_req_type
  type uv_loop_t = struct_uv_loop_s
  type uv_handle_t = struct_uv_handle_s
  type uv_stream_t = struct_uv_stream_s
  type uv_tcp_t = struct_uv_tcp_s
  type uv_udp_t = struct_uv_udp_s
  type uv_pipe_t = struct_uv_pipe_s
  type uv_tty_t = struct_uv_tty_s
  type uv_poll_t = struct_uv_poll_s
  type uv_timer_t = struct_uv_timer_s
  type uv_prepare_t = struct_uv_prepare_s
  type uv_check_t = struct_uv_check_s
  type uv_idle_t = struct_uv_idle_s
  type uv_async_t = struct_uv_async_s
  type uv_process_t = struct_uv_process_s
  type uv_fs_event_t = struct_uv_fs_event_s
  type uv_fs_poll_t = struct_uv_fs_poll_s
  type uv_signal_t = struct_uv_signal_s
  type uv_req_t = struct_uv_req_s
  type uv_getaddrinfo_t = struct_uv_getaddrinfo_s
  type uv_getnameinfo_t = struct_uv_getnameinfo_s
  type uv_shutdown_t = struct_uv_shutdown_s
  type uv_write_t = struct_uv_write_s
  type uv_connect_t = struct_uv_connect_s
  type uv_udp_send_t = struct_uv_udp_send_s
  type uv_fs_t = struct_uv_fs_s
  type uv_work_t = struct_uv_work_s
  type uv_cpu_info_t = struct_uv_cpu_info_s
  type uv_interface_address_t = struct_uv_interface_address_s
  type uv_dirent_t = struct_uv_dirent_s
  type enum_uv_loop_option = native.CInt
  val enum_uv_loop_option_UV_LOOP_BLOCK_SIGNAL = 0
  type uv_loop_option = enum_uv_loop_option
  type enum_uv_run_mode = native.CInt
  val enum_uv_run_mode_UV_RUN_DEFAULT = 0
  val enum_uv_run_mode_UV_RUN_ONCE = 1
  val enum_uv_run_mode_UV_RUN_NOWAIT = 2
  type uv_run_mode = enum_uv_run_mode
  def uv_version(): native.CUnsignedInt = native.extern
  def uv_version_string(): native.Ptr[native.CChar] = native.extern
  type uv_malloc_func = native.CFunctionPtr1[native.Ptr[Byte],native.CInt]
  type uv_realloc_func = native.CFunctionPtr2[native.Ptr[Byte],native.Ptr[Byte],native.CInt]
  type uv_calloc_func = native.CFunctionPtr2[native.Ptr[Byte],native.CInt,native.CInt]
  type uv_free_func = native.CFunctionPtr1[Unit,native.Ptr[Byte]]
  def uv_replace_allocator(malloc_func: native.CFunctionPtr1[native.Ptr[Byte],native.CInt], realloc_func: native.CFunctionPtr2[native.Ptr[Byte],native.Ptr[Byte],native.CInt], calloc_func: native.CFunctionPtr2[native.Ptr[Byte],native.CInt,native.CInt], free_func: native.CFunctionPtr1[Unit,native.Ptr[Byte]]): native.CInt = native.extern
  def uv_default_loop(): native.Ptr[uv_loop_t] = native.extern
  def uv_loop_init(loop: native.Ptr[uv_loop_t]): native.CInt = native.extern
  def uv_loop_close(loop: native.Ptr[uv_loop_t]): native.CInt = native.extern
  def uv_loop_new(): native.Ptr[uv_loop_t] = native.extern
  def uv_loop_delete(anonymous: native.Ptr[uv_loop_t]): Unit = native.extern
  def uv_loop_size(): native.CInt = native.extern
  def uv_loop_alive(loop: native.Ptr[const_uv_loop_t]): native.CInt = native.extern
  def uv_loop_configure(loop: native.Ptr[uv_loop_t], option: uv_loop_option): native.CInt = native.extern
  def uv_run(anonymous: native.Ptr[uv_loop_t], mode: uv_run_mode): native.CInt = native.extern
  def uv_stop(anonymous: native.Ptr[uv_loop_t]): Unit = native.extern
  def uv_ref(anonymous: native.Ptr[uv_handle_t]): Unit = native.extern
  def uv_unref(anonymous: native.Ptr[uv_handle_t]): Unit = native.extern
  def uv_has_ref(anonymous: native.Ptr[const_uv_handle_t]): native.CInt = native.extern
  def uv_update_time(anonymous: native.Ptr[uv_loop_t]): Unit = native.extern
  def uv_now(anonymous: native.Ptr[const_uv_loop_t]): native.CInt = native.extern
  def uv_backend_fd(anonymous: native.Ptr[const_uv_loop_t]): native.CInt = native.extern
  def uv_backend_timeout(anonymous: native.Ptr[const_uv_loop_t]): native.CInt = native.extern
  type uv_alloc_cb = native.CFunctionPtr3[Unit,native.Ptr[uv_handle_t],native.CInt,native.Ptr[native.CInt]]
  type uv_read_cb = native.CFunctionPtr3[Unit,native.Ptr[uv_stream_t],native.CInt,native.Ptr[native.CInt]]
  type uv_write_cb = native.CFunctionPtr2[Unit,native.Ptr[uv_write_t],native.CInt]
  type uv_connect_cb = native.CFunctionPtr2[Unit,native.Ptr[uv_connect_t],native.CInt]
  type uv_shutdown_cb = native.CFunctionPtr2[Unit,native.Ptr[uv_shutdown_t],native.CInt]
  type uv_connection_cb = native.CFunctionPtr2[Unit,native.Ptr[uv_stream_t],native.CInt]
  type uv_close_cb = native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]]
  type uv_poll_cb = native.CFunctionPtr3[Unit,native.Ptr[uv_poll_t],native.CInt,native.CInt]
  type uv_timer_cb = native.CFunctionPtr1[Unit,native.Ptr[uv_timer_t]]
  type uv_async_cb = native.CFunctionPtr1[Unit,native.Ptr[uv_async_t]]
  type uv_prepare_cb = native.CFunctionPtr1[Unit,native.Ptr[uv_prepare_t]]
  type uv_check_cb = native.CFunctionPtr1[Unit,native.Ptr[uv_check_t]]
  type uv_idle_cb = native.CFunctionPtr1[Unit,native.Ptr[uv_idle_t]]
  type uv_exit_cb = native.CFunctionPtr3[Unit,native.Ptr[uv_process_t],native.CInt,native.CInt]
  type uv_walk_cb = native.CFunctionPtr2[Unit,native.Ptr[uv_handle_t],native.Ptr[Byte]]
  type uv_fs_cb = native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]
  type uv_work_cb = native.CFunctionPtr1[Unit,native.Ptr[uv_work_t]]
  type uv_after_work_cb = native.CFunctionPtr2[Unit,native.Ptr[uv_work_t],native.CInt]
  type uv_getaddrinfo_cb = native.CFunctionPtr3[Unit,native.Ptr[uv_getaddrinfo_t],native.CInt,native.Ptr[struct_addrinfo]]
  type uv_getnameinfo_cb = native.CFunctionPtr4[Unit,native.Ptr[uv_getnameinfo_t],native.CInt,native.Ptr[native.CChar],native.Ptr[native.CChar]]
  type struct_uv_timespec_t = native.CStruct2[native.CLong,native.CLong]
  type uv_timespec_t = struct_uv_timespec_t
  type struct_struct (anonymous at /home/marius/clang-llvm/build2/uv.h:309:9) = native.CStruct16[native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,uv_timespec_t,uv_timespec_t,uv_timespec_t,uv_timespec_t]
  type uv_stat_t = struct_(anonymous struct at /home/marius/clang-llvm/build2/uv.h:309:9)
  type uv_fs_event_cb = native.CFunctionPtr4[Unit,native.Ptr[uv_fs_event_t],native.Ptr[native.CChar],native.CInt,native.CInt]
  type uv_fs_poll_cb = native.CFunctionPtr4[Unit,native.Ptr[uv_fs_poll_t],native.CInt,native.Ptr[const_uv_stat_t],native.Ptr[const_uv_stat_t]]
  type uv_signal_cb = native.CFunctionPtr2[Unit,native.Ptr[uv_signal_t],native.CInt]
  type enum_uv_membership = native.CInt
  val enum_uv_membership_UV_LEAVE_GROUP = 0
  val enum_uv_membership_UV_JOIN_GROUP = 1
  type uv_membership = enum_uv_membership
  def uv_strerror(err: native.CInt): native.Ptr[native.CChar] = native.extern
  def uv_err_name(err: native.CInt): native.Ptr[native.CChar] = native.extern
  type struct_uv_req_s = native.CStruct5[native.Ptr[Byte],uv_req_type,void *[2],void *[4],native.CInt]
  type struct_uv_shutdown_s = native.CStruct7[native.Ptr[Byte],uv_req_type,void *[2],void *[4],native.CInt,native.CFunctionPtr2[Unit,native.Ptr[uv_shutdown_t],native.CInt],native.CInt]
  type struct_uv_handle_s = native.CStruct7[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:401:3),native.CInt]
  def uv_handle_size(type: uv_handle_type): native.CInt = native.extern
  def uv_req_size(type: uv_req_type): native.CInt = native.extern
  def uv_is_active(handle: native.Ptr[const_uv_handle_t]): native.CInt = native.extern
  def uv_walk(loop: native.Ptr[uv_loop_t], walk_cb: native.CFunctionPtr2[Unit,native.Ptr[uv_handle_t],native.Ptr[Byte]], arg: native.Ptr[Byte]): Unit = native.extern
  def uv_print_all_handles(loop: native.Ptr[uv_loop_t], stream: native.Ptr[native.CInt]): Unit = native.extern
  def uv_print_active_handles(loop: native.Ptr[uv_loop_t], stream: native.Ptr[native.CInt]): Unit = native.extern
  def uv_close(handle: native.Ptr[uv_handle_t], close_cb: native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]]): Unit = native.extern
  def uv_send_buffer_size(handle: native.Ptr[uv_handle_t], value: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_recv_buffer_size(handle: native.Ptr[uv_handle_t], value: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_fileno(handle: native.Ptr[const_uv_handle_t], fd: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_buf_init(base: native.Ptr[native.CChar], len: native.CUnsignedInt): native.CInt = native.extern
  type struct_uv_stream_s = native.CStruct10[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:441:3),native.CInt,native.CFunctionPtr3[Unit,native.Ptr[uv_handle_t],native.CInt,native.Ptr[native.CInt]],native.CFunctionPtr3[Unit,native.Ptr[uv_stream_t],native.CInt,native.Ptr[native.CInt]],native.CInt]
  def uv_listen(stream: native.Ptr[uv_stream_t], backlog: native.CInt, cb: native.CFunctionPtr2[Unit,native.Ptr[uv_stream_t],native.CInt]): native.CInt = native.extern
  def uv_accept(server: native.Ptr[uv_stream_t], client: native.Ptr[uv_stream_t]): native.CInt = native.extern
  def uv_read_start(anonymous: native.Ptr[uv_stream_t], alloc_cb: native.CFunctionPtr3[Unit,native.Ptr[uv_handle_t],native.CInt,native.Ptr[native.CInt]], read_cb: native.CFunctionPtr3[Unit,native.Ptr[uv_stream_t],native.CInt,native.Ptr[native.CInt]]): native.CInt = native.extern
  def uv_read_stop(anonymous: native.Ptr[uv_stream_t]): native.CInt = native.extern
  def uv_write(req: native.Ptr[uv_write_t], handle: native.Ptr[uv_stream_t], bufs: native.Ptr[native.CInt], nbufs: native.CUnsignedInt, cb: native.CFunctionPtr2[Unit,native.Ptr[uv_write_t],native.CInt]): native.CInt = native.extern
  def uv_write2(req: native.Ptr[uv_write_t], handle: native.Ptr[uv_stream_t], bufs: native.Ptr[native.CInt], nbufs: native.CUnsignedInt, send_handle: native.Ptr[uv_stream_t], cb: native.CFunctionPtr2[Unit,native.Ptr[uv_write_t],native.CInt]): native.CInt = native.extern
  def uv_try_write(handle: native.Ptr[uv_stream_t], bufs: native.Ptr[native.CInt], nbufs: native.CUnsignedInt): native.CInt = native.extern
  type struct_uv_write_s = native.CStruct8[native.Ptr[Byte],uv_req_type,void *[2],void *[4],native.CInt,native.Ptr[uv_stream_t],native.Ptr[uv_stream_t],native.CInt]
  def uv_is_readable(handle: native.Ptr[const_uv_stream_t]): native.CInt = native.extern
  def uv_is_writable(handle: native.Ptr[const_uv_stream_t]): native.CInt = native.extern
  def uv_stream_set_blocking(handle: native.Ptr[uv_stream_t], blocking: native.CInt): native.CInt = native.extern
  def uv_is_closing(handle: native.Ptr[const_uv_handle_t]): native.CInt = native.extern
  type struct_uv_tcp_s = native.CStruct10[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:492:3),native.CInt,native.CFunctionPtr3[Unit,native.Ptr[uv_handle_t],native.CInt,native.Ptr[native.CInt]],native.CFunctionPtr3[Unit,native.Ptr[uv_stream_t],native.CInt,native.Ptr[native.CInt]],native.CInt]
  def uv_tcp_init(anonymous: native.Ptr[uv_loop_t], handle: native.Ptr[uv_tcp_t]): native.CInt = native.extern
  def uv_tcp_init_ex(anonymous: native.Ptr[uv_loop_t], handle: native.Ptr[uv_tcp_t], flags: native.CUnsignedInt): native.CInt = native.extern
  def uv_tcp_open(handle: native.Ptr[uv_tcp_t], sock: native.CInt): native.CInt = native.extern
  def uv_tcp_nodelay(handle: native.Ptr[uv_tcp_t], enable: native.CInt): native.CInt = native.extern
  def uv_tcp_keepalive(handle: native.Ptr[uv_tcp_t], enable: native.CInt, delay: native.CUnsignedInt): native.CInt = native.extern
  def uv_tcp_simultaneous_accepts(handle: native.Ptr[uv_tcp_t], enable: native.CInt): native.CInt = native.extern
  type enum_uv_tcp_flags = native.CInt
  val enum_uv_tcp_flags_UV_TCP_IPV6ONLY = 0
  def uv_tcp_bind(handle: native.Ptr[uv_tcp_t], addr: native.Ptr[const_struct sockaddr], flags: native.CUnsignedInt): native.CInt = native.extern
  def uv_tcp_getsockname(handle: native.Ptr[const_uv_tcp_t], name: native.Ptr[struct_sockaddr], namelen: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_tcp_getpeername(handle: native.Ptr[const_uv_tcp_t], name: native.Ptr[struct_sockaddr], namelen: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_tcp_connect(req: native.Ptr[uv_connect_t], handle: native.Ptr[uv_tcp_t], addr: native.Ptr[const_struct sockaddr], cb: native.CFunctionPtr2[Unit,native.Ptr[uv_connect_t],native.CInt]): native.CInt = native.extern
  type struct_uv_connect_s = native.CStruct7[native.Ptr[Byte],uv_req_type,void *[2],void *[4],native.CInt,native.Ptr[uv_stream_t],native.CInt]
  type enum_uv_udp_flags = native.CInt
  val enum_uv_udp_flags_UV_UDP_IPV6ONLY = 0
  val enum_uv_udp_flags_UV_UDP_PARTIAL = 1
  val enum_uv_udp_flags_UV_UDP_REUSEADDR = 2
  type uv_udp_send_cb = native.CFunctionPtr2[Unit,native.Ptr[uv_udp_send_t],native.CInt]
  type uv_udp_recv_cb = native.CFunctionPtr5[Unit,native.Ptr[uv_udp_t],native.CInt,native.Ptr[native.CInt],native.Ptr[const_struct sockaddr],native.CUnsignedInt]
  type struct_uv_udp_s = native.CStruct9[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:566:3),native.CInt,native.CInt,native.CInt]
  type struct_uv_udp_send_s = native.CStruct7[native.Ptr[Byte],uv_req_type,void *[2],void *[4],native.CInt,native.CFunctionPtr2[Unit,native.Ptr[uv_udp_send_t],native.CInt],native.CInt]
  def uv_udp_init(anonymous: native.Ptr[uv_loop_t], handle: native.Ptr[uv_udp_t]): native.CInt = native.extern
  def uv_udp_init_ex(anonymous: native.Ptr[uv_loop_t], handle: native.Ptr[uv_udp_t], flags: native.CUnsignedInt): native.CInt = native.extern
  def uv_udp_open(handle: native.Ptr[uv_udp_t], sock: native.CInt): native.CInt = native.extern
  def uv_udp_bind(handle: native.Ptr[uv_udp_t], addr: native.Ptr[const_struct sockaddr], flags: native.CUnsignedInt): native.CInt = native.extern
  def uv_udp_getsockname(handle: native.Ptr[const_uv_udp_t], name: native.Ptr[struct_sockaddr], namelen: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_udp_set_membership(handle: native.Ptr[uv_udp_t], multicast_addr: native.Ptr[native.CChar], interface_addr: native.Ptr[native.CChar], membership: uv_membership): native.CInt = native.extern
  def uv_udp_set_multicast_loop(handle: native.Ptr[uv_udp_t], on: native.CInt): native.CInt = native.extern
  def uv_udp_set_multicast_ttl(handle: native.Ptr[uv_udp_t], ttl: native.CInt): native.CInt = native.extern
  def uv_udp_set_multicast_interface(handle: native.Ptr[uv_udp_t], interface_addr: native.Ptr[native.CChar]): native.CInt = native.extern
  def uv_udp_set_broadcast(handle: native.Ptr[uv_udp_t], on: native.CInt): native.CInt = native.extern
  def uv_udp_set_ttl(handle: native.Ptr[uv_udp_t], ttl: native.CInt): native.CInt = native.extern
  def uv_udp_send(req: native.Ptr[uv_udp_send_t], handle: native.Ptr[uv_udp_t], bufs: native.Ptr[native.CInt], nbufs: native.CUnsignedInt, addr: native.Ptr[const_struct sockaddr], send_cb: native.CFunctionPtr2[Unit,native.Ptr[uv_udp_send_t],native.CInt]): native.CInt = native.extern
  def uv_udp_try_send(handle: native.Ptr[uv_udp_t], bufs: native.Ptr[native.CInt], nbufs: native.CUnsignedInt, addr: native.Ptr[const_struct sockaddr]): native.CInt = native.extern
  def uv_udp_recv_start(handle: native.Ptr[uv_udp_t], alloc_cb: native.CFunctionPtr3[Unit,native.Ptr[uv_handle_t],native.CInt,native.Ptr[native.CInt]], recv_cb: native.CFunctionPtr5[Unit,native.Ptr[uv_udp_t],native.CInt,native.Ptr[native.CInt],native.Ptr[const_struct sockaddr],native.CUnsignedInt]): native.CInt = native.extern
  def uv_udp_recv_stop(handle: native.Ptr[uv_udp_t]): native.CInt = native.extern
  type struct_uv_tty_s = native.CStruct10[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:630:3),native.CInt,native.CFunctionPtr3[Unit,native.Ptr[uv_handle_t],native.CInt,native.Ptr[native.CInt]],native.CFunctionPtr3[Unit,native.Ptr[uv_stream_t],native.CInt,native.Ptr[native.CInt]],native.CInt]
  type enum_uv_tty_mode_t = native.CInt
  val enum_uv_tty_mode_t_UV_TTY_MODE_NORMAL = 0
  val enum_uv_tty_mode_t_UV_TTY_MODE_RAW = 1
  val enum_uv_tty_mode_t_UV_TTY_MODE_IO = 2
  type uv_tty_mode_t = enum_uv_tty_mode_t
  def uv_tty_init(anonymous: native.Ptr[uv_loop_t], anonymous: native.Ptr[uv_tty_t], fd: native.CInt, readable: native.CInt): native.CInt = native.extern
  def uv_tty_set_mode(anonymous: native.Ptr[uv_tty_t], mode: uv_tty_mode_t): native.CInt = native.extern
  def uv_tty_reset_mode(): native.CInt = native.extern
  def uv_tty_get_winsize(anonymous: native.Ptr[uv_tty_t], width: native.Ptr[native.CInt], height: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_guess_handle(file: native.CInt): uv_handle_type = native.extern
  type struct_uv_pipe_s = native.CStruct11[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:668:3),native.CInt,native.CFunctionPtr3[Unit,native.Ptr[uv_handle_t],native.CInt,native.Ptr[native.CInt]],native.CFunctionPtr3[Unit,native.Ptr[uv_stream_t],native.CInt,native.Ptr[native.CInt]],native.CInt,native.CInt]
  def uv_pipe_init(anonymous: native.Ptr[uv_loop_t], handle: native.Ptr[uv_pipe_t], ipc: native.CInt): native.CInt = native.extern
  def uv_pipe_open(anonymous: native.Ptr[uv_pipe_t], file: native.CInt): native.CInt = native.extern
  def uv_pipe_bind(handle: native.Ptr[uv_pipe_t], name: native.Ptr[native.CChar]): native.CInt = native.extern
  def uv_pipe_connect(req: native.Ptr[uv_connect_t], handle: native.Ptr[uv_pipe_t], name: native.Ptr[native.CChar], cb: native.CFunctionPtr2[Unit,native.Ptr[uv_connect_t],native.CInt]): Unit = native.extern
  def uv_pipe_getsockname(handle: native.Ptr[const_uv_pipe_t], buffer: native.Ptr[native.CChar], size: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_pipe_getpeername(handle: native.Ptr[const_uv_pipe_t], buffer: native.Ptr[native.CChar], size: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_pipe_pending_instances(handle: native.Ptr[uv_pipe_t], count: native.CInt): Unit = native.extern
  def uv_pipe_pending_count(handle: native.Ptr[uv_pipe_t]): native.CInt = native.extern
  def uv_pipe_pending_type(handle: native.Ptr[uv_pipe_t]): uv_handle_type = native.extern
  type struct_uv_poll_s = native.CStruct8[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:693:3),native.CInt,native.CInt]
  type enum_uv_poll_event = native.CInt
  val enum_uv_poll_event_UV_READABLE = 0
  val enum_uv_poll_event_UV_WRITABLE = 1
  def uv_poll_init(loop: native.Ptr[uv_loop_t], handle: native.Ptr[uv_poll_t], fd: native.CInt): native.CInt = native.extern
  def uv_poll_init_socket(loop: native.Ptr[uv_loop_t], handle: native.Ptr[uv_poll_t], socket: native.CInt): native.CInt = native.extern
  def uv_poll_start(handle: native.Ptr[uv_poll_t], events: native.CInt, cb: native.CFunctionPtr3[Unit,native.Ptr[uv_poll_t],native.CInt,native.CInt]): native.CInt = native.extern
  def uv_poll_stop(handle: native.Ptr[uv_poll_t]): native.CInt = native.extern
  type struct_uv_prepare_s = native.CStruct7[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:712:3),native.CInt]
  def uv_prepare_init(anonymous: native.Ptr[uv_loop_t], prepare: native.Ptr[uv_prepare_t]): native.CInt = native.extern
  def uv_prepare_start(prepare: native.Ptr[uv_prepare_t], cb: native.CFunctionPtr1[Unit,native.Ptr[uv_prepare_t]]): native.CInt = native.extern
  def uv_prepare_stop(prepare: native.Ptr[uv_prepare_t]): native.CInt = native.extern
  type struct_uv_check_s = native.CStruct7[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:722:3),native.CInt]
  def uv_check_init(anonymous: native.Ptr[uv_loop_t], check: native.Ptr[uv_check_t]): native.CInt = native.extern
  def uv_check_start(check: native.Ptr[uv_check_t], cb: native.CFunctionPtr1[Unit,native.Ptr[uv_check_t]]): native.CInt = native.extern
  def uv_check_stop(check: native.Ptr[uv_check_t]): native.CInt = native.extern
  type struct_uv_idle_s = native.CStruct7[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:732:3),native.CInt]
  def uv_idle_init(anonymous: native.Ptr[uv_loop_t], idle: native.Ptr[uv_idle_t]): native.CInt = native.extern
  def uv_idle_start(idle: native.Ptr[uv_idle_t], cb: native.CFunctionPtr1[Unit,native.Ptr[uv_idle_t]]): native.CInt = native.extern
  def uv_idle_stop(idle: native.Ptr[uv_idle_t]): native.CInt = native.extern
  type struct_uv_async_s = native.CStruct7[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:742:3),native.CInt]
  def uv_async_init(anonymous: native.Ptr[uv_loop_t], async: native.Ptr[uv_async_t], async_cb: native.CFunctionPtr1[Unit,native.Ptr[uv_async_t]]): native.CInt = native.extern
  def uv_async_send(async: native.Ptr[uv_async_t]): native.CInt = native.extern
  type struct_uv_timer_s = native.CStruct7[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:758:3),native.CInt]
  def uv_timer_init(anonymous: native.Ptr[uv_loop_t], handle: native.Ptr[uv_timer_t]): native.CInt = native.extern
  def uv_timer_start(handle: native.Ptr[uv_timer_t], cb: native.CFunctionPtr1[Unit,native.Ptr[uv_timer_t]], timeout: native.CInt, repeat: native.CInt): native.CInt = native.extern
  def uv_timer_stop(handle: native.Ptr[uv_timer_t]): native.CInt = native.extern
  def uv_timer_again(handle: native.Ptr[uv_timer_t]): native.CInt = native.extern
  def uv_timer_set_repeat(handle: native.Ptr[uv_timer_t], repeat: native.CInt): Unit = native.extern
  def uv_timer_get_repeat(handle: native.Ptr[const_uv_timer_t]): native.CInt = native.extern
  type struct_uv_getaddrinfo_s = native.CStruct6[native.Ptr[Byte],uv_req_type,void *[2],void *[4],native.CInt,native.CInt]
  def uv_getaddrinfo(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_getaddrinfo_t], getaddrinfo_cb: native.CFunctionPtr3[Unit,native.Ptr[uv_getaddrinfo_t],native.CInt,native.Ptr[struct_addrinfo]], node: native.Ptr[native.CChar], service: native.Ptr[native.CChar], hints: native.Ptr[const_struct addrinfo]): native.CInt = native.extern
  def uv_freeaddrinfo(ai: native.Ptr[struct_addrinfo]): Unit = native.extern
  type struct_uv_getnameinfo_s = native.CStruct6[native.Ptr[Byte],uv_req_type,void *[2],void *[4],native.CInt,native.CInt]
  def uv_getnameinfo(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_getnameinfo_t], getnameinfo_cb: native.CFunctionPtr4[Unit,native.Ptr[uv_getnameinfo_t],native.CInt,native.Ptr[native.CChar],native.Ptr[native.CChar]], addr: native.Ptr[const_struct sockaddr], flags: native.CInt): native.CInt = native.extern
  type enum_uv_stdio_flags = native.CInt
  val enum_uv_stdio_flags_UV_IGNORE = 0
  val enum_uv_stdio_flags_UV_CREATE_PIPE = 1
  val enum_uv_stdio_flags_UV_INHERIT_FD = 2
  val enum_uv_stdio_flags_UV_INHERIT_STREAM = 3
  val enum_uv_stdio_flags_UV_READABLE_PIPE = 4
  val enum_uv_stdio_flags_UV_WRITABLE_PIPE = 5
  type uv_stdio_flags = enum_uv_stdio_flags
  type struct_uv_stdio_container_s = native.CStruct2[uv_stdio_flags,union (anonymous union at /home/marius/clang-llvm/build2/uv.h:835:3)]
  type uv_stdio_container_t = struct_uv_stdio_container_s
  type struct_uv_process_options_s = native.CStruct10[native.CFunctionPtr3[Unit,native.Ptr[uv_process_t],native.CInt,native.CInt],native.Ptr[native.CChar],native.Ptr[native.Ptr[native.CChar]],native.Ptr[native.Ptr[native.CChar]],native.Ptr[native.CChar],native.CUnsignedInt,native.CInt,native.Ptr[uv_stdio_container_t],native.CInt,native.CInt]
  type uv_process_options_t = struct_uv_process_options_s
  type enum_uv_process_flags = native.CInt
  val enum_uv_process_flags_UV_PROCESS_SETUID = 0
  val enum_uv_process_flags_UV_PROCESS_SETGID = 1
  val enum_uv_process_flags_UV_PROCESS_WINDOWS_VERBATIM_ARGUMENTS = 2
  val enum_uv_process_flags_UV_PROCESS_DETACHED = 3
  val enum_uv_process_flags_UV_PROCESS_WINDOWS_HIDE = 4
  type struct_uv_process_s = native.CStruct9[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:928:3),native.CInt,native.CInt,native.CInt]
  def uv_spawn(loop: native.Ptr[uv_loop_t], handle: native.Ptr[uv_process_t], options: native.Ptr[const_uv_process_options_t]): native.CInt = native.extern
  def uv_process_kill(anonymous: native.Ptr[uv_process_t], signum: native.CInt): native.CInt = native.extern
  def uv_kill(pid: native.CInt, signum: native.CInt): native.CInt = native.extern
  type struct_uv_work_s = native.CStruct8[native.Ptr[Byte],uv_req_type,void *[2],void *[4],native.CInt,native.CFunctionPtr1[Unit,native.Ptr[uv_work_t]],native.CFunctionPtr2[Unit,native.Ptr[uv_work_t],native.CInt],native.CInt]
  def uv_queue_work(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_work_t], work_cb: native.CFunctionPtr1[Unit,native.Ptr[uv_work_t]], after_work_cb: native.CFunctionPtr2[Unit,native.Ptr[uv_work_t],native.CInt]): native.CInt = native.extern
  def uv_cancel(req: native.Ptr[uv_req_t]): native.CInt = native.extern
  type struct_uv_cpu_info_s = native.CStruct3[native.Ptr[native.CChar],native.CInt,struct_uv_cpu_times_s]
  type struct_uv_cpu_times_s = native.CStruct5[native.CInt,native.CInt,native.CInt,native.CInt,native.CInt]
  type struct_uv_interface_address_s = native.CStruct5[native.Ptr[native.CChar],char [6],native.CInt,union (anonymous union at /home/marius/clang-llvm/build2/uv.h:976:3),union (anonymous union at /home/marius/clang-llvm/build2/uv.h:980:3)]
  type enum_uv_dirent_type_t = native.CInt
  val enum_uv_dirent_type_t_UV_DIRENT_UNKNOWN = 0
  val enum_uv_dirent_type_t_UV_DIRENT_FILE = 1
  val enum_uv_dirent_type_t_UV_DIRENT_DIR = 2
  val enum_uv_dirent_type_t_UV_DIRENT_LINK = 3
  val enum_uv_dirent_type_t_UV_DIRENT_FIFO = 4
  val enum_uv_dirent_type_t_UV_DIRENT_SOCKET = 5
  val enum_uv_dirent_type_t_UV_DIRENT_CHAR = 6
  val enum_uv_dirent_type_t_UV_DIRENT_BLOCK = 7
  type uv_dirent_type_t = enum_uv_dirent_type_t
  type struct_uv_dirent_s = native.CStruct2[native.Ptr[native.CChar],uv_dirent_type_t]
  def uv_setup_args(argc: native.CInt, argv: native.Ptr[native.Ptr[native.CChar]]): native.Ptr[native.Ptr[native.CChar]] = native.extern
  def uv_get_process_title(buffer: native.Ptr[native.CChar], size: native.CInt): native.CInt = native.extern
  def uv_set_process_title(title: native.Ptr[native.CChar]): native.CInt = native.extern
  def uv_resident_set_memory(rss: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_uptime(uptime: native.Ptr[native.CDouble]): native.CInt = native.extern
  type struct_uv_timeval_t = native.CStruct2[native.CLong,native.CLong]
  type uv_timeval_t = struct_uv_timeval_t
  type struct_struct (anonymous at /home/marius/clang-llvm/build2/uv.h:1013:9) = native.CStruct16[uv_timeval_t,uv_timeval_t,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt,native.CInt]
  type uv_rusage_t = struct_(anonymous struct at /home/marius/clang-llvm/build2/uv.h:1013:9)
  def uv_getrusage(rusage: native.Ptr[uv_rusage_t]): native.CInt = native.extern
  def uv_os_homedir(buffer: native.Ptr[native.CChar], size: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_cpu_info(cpu_infos: native.Ptr[native.Ptr[uv_cpu_info_t]], count: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_free_cpu_info(cpu_infos: native.Ptr[uv_cpu_info_t], count: native.CInt): Unit = native.extern
  def uv_interface_addresses(addresses: native.Ptr[native.Ptr[uv_interface_address_t]], count: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_free_interface_addresses(addresses: native.Ptr[uv_interface_address_t], count: native.CInt): Unit = native.extern
  type enum_uv_fs_type = native.CInt
  val enum_uv_fs_type_UV_FS_UNKNOWN = 0
  val enum_uv_fs_type_UV_FS_CUSTOM = 1
  val enum_uv_fs_type_UV_FS_OPEN = 2
  val enum_uv_fs_type_UV_FS_CLOSE = 3
  val enum_uv_fs_type_UV_FS_READ = 4
  val enum_uv_fs_type_UV_FS_WRITE = 5
  val enum_uv_fs_type_UV_FS_SENDFILE = 6
  val enum_uv_fs_type_UV_FS_STAT = 7
  val enum_uv_fs_type_UV_FS_LSTAT = 8
  val enum_uv_fs_type_UV_FS_FSTAT = 9
  val enum_uv_fs_type_UV_FS_FTRUNCATE = 10
  val enum_uv_fs_type_UV_FS_UTIME = 11
  val enum_uv_fs_type_UV_FS_FUTIME = 12
  val enum_uv_fs_type_UV_FS_ACCESS = 13
  val enum_uv_fs_type_UV_FS_CHMOD = 14
  val enum_uv_fs_type_UV_FS_FCHMOD = 15
  val enum_uv_fs_type_UV_FS_FSYNC = 16
  val enum_uv_fs_type_UV_FS_FDATASYNC = 17
  val enum_uv_fs_type_UV_FS_UNLINK = 18
  val enum_uv_fs_type_UV_FS_RMDIR = 19
  val enum_uv_fs_type_UV_FS_MKDIR = 20
  val enum_uv_fs_type_UV_FS_MKDTEMP = 21
  val enum_uv_fs_type_UV_FS_RENAME = 22
  val enum_uv_fs_type_UV_FS_SCANDIR = 23
  val enum_uv_fs_type_UV_FS_LINK = 24
  val enum_uv_fs_type_UV_FS_SYMLINK = 25
  val enum_uv_fs_type_UV_FS_READLINK = 26
  val enum_uv_fs_type_UV_FS_CHOWN = 27
  val enum_uv_fs_type_UV_FS_FCHOWN = 28
  val enum_uv_fs_type_UV_FS_REALPATH = 29
  type uv_fs_type = enum_uv_fs_type
  type struct_uv_fs_s = native.CStruct12[native.Ptr[Byte],uv_req_type,void *[2],void *[4],native.CInt,native.Ptr[uv_loop_t],native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]],native.CInt,native.Ptr[Byte],native.Ptr[native.CChar],uv_stat_t,native.CInt]
  def uv_fs_req_cleanup(req: native.Ptr[uv_fs_t]): Unit = native.extern
  def uv_fs_close(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], file: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_open(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], flags: native.CInt, mode: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_read(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], file: native.CInt, bufs: native.Ptr[native.CInt], nbufs: native.CUnsignedInt, offset: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_unlink(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_write(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], file: native.CInt, bufs: native.Ptr[native.CInt], nbufs: native.CUnsignedInt, offset: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_mkdir(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], mode: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_mkdtemp(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], tpl: native.Ptr[native.CChar], cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_rmdir(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_scandir(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], flags: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_scandir_next(req: native.Ptr[uv_fs_t], ent: native.Ptr[uv_dirent_t]): native.CInt = native.extern
  def uv_fs_stat(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_fstat(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], file: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_rename(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], new_path: native.Ptr[native.CChar], cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_fsync(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], file: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_fdatasync(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], file: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_ftruncate(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], file: native.CInt, offset: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_sendfile(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], out_fd: native.CInt, in_fd: native.CInt, in_offset: native.CInt, length: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_access(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], mode: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_chmod(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], mode: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_utime(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], atime: native.CDouble, mtime: native.CDouble, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_futime(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], file: native.CInt, atime: native.CDouble, mtime: native.CDouble, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_lstat(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_link(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], new_path: native.Ptr[native.CChar], cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_symlink(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], new_path: native.Ptr[native.CChar], flags: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_readlink(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_realpath(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_fchmod(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], file: native.CInt, mode: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_chown(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], path: native.Ptr[native.CChar], uid: native.CInt, gid: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  def uv_fs_fchown(loop: native.Ptr[uv_loop_t], req: native.Ptr[uv_fs_t], file: native.CInt, uid: native.CInt, gid: native.CInt, cb: native.CFunctionPtr1[Unit,native.Ptr[uv_fs_t]]): native.CInt = native.extern
  type enum_uv_fs_event = native.CInt
  val enum_uv_fs_event_UV_RENAME = 0
  val enum_uv_fs_event_UV_CHANGE = 1
  type struct_uv_fs_event_s = native.CStruct8[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:1257:3),native.CInt,native.CInt]
  type struct_uv_fs_poll_s = native.CStruct7[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:1268:3),native.CInt]
  def uv_fs_poll_init(loop: native.Ptr[uv_loop_t], handle: native.Ptr[uv_fs_poll_t]): native.CInt = native.extern
  def uv_fs_poll_start(handle: native.Ptr[uv_fs_poll_t], poll_cb: native.CFunctionPtr4[Unit,native.Ptr[uv_fs_poll_t],native.CInt,native.Ptr[const_uv_stat_t],native.Ptr[const_uv_stat_t]], path: native.Ptr[native.CChar], interval: native.CUnsignedInt): native.CInt = native.extern
  def uv_fs_poll_stop(handle: native.Ptr[uv_fs_poll_t]): native.CInt = native.extern
  def uv_fs_poll_getpath(handle: native.Ptr[uv_fs_poll_t], buffer: native.Ptr[native.CChar], size: native.Ptr[native.CInt]): native.CInt = native.extern
  type struct_uv_signal_s = native.CStruct9[native.Ptr[Byte],native.Ptr[uv_loop_t],uv_handle_type,native.CFunctionPtr1[Unit,native.Ptr[uv_handle_t]],void *[2],union (anonymous union at /home/marius/clang-llvm/build2/uv.h:1285:3),native.CInt,native.CInt,native.CInt]
  def uv_signal_init(loop: native.Ptr[uv_loop_t], handle: native.Ptr[uv_signal_t]): native.CInt = native.extern
  def uv_signal_start(handle: native.Ptr[uv_signal_t], signal_cb: native.CFunctionPtr2[Unit,native.Ptr[uv_signal_t],native.CInt], signum: native.CInt): native.CInt = native.extern
  def uv_signal_stop(handle: native.Ptr[uv_signal_t]): native.CInt = native.extern
  def uv_loadavg(avg: native.Ptr[native.CDouble]): Unit = native.extern
  type enum_uv_fs_event_flags = native.CInt
  val enum_uv_fs_event_flags_UV_FS_EVENT_WATCH_ENTRY = 0
  val enum_uv_fs_event_flags_UV_FS_EVENT_STAT = 1
  val enum_uv_fs_event_flags_UV_FS_EVENT_RECURSIVE = 2
  def uv_fs_event_init(loop: native.Ptr[uv_loop_t], handle: native.Ptr[uv_fs_event_t]): native.CInt = native.extern
  def uv_fs_event_start(handle: native.Ptr[uv_fs_event_t], cb: native.CFunctionPtr4[Unit,native.Ptr[uv_fs_event_t],native.Ptr[native.CChar],native.CInt,native.CInt], path: native.Ptr[native.CChar], flags: native.CUnsignedInt): native.CInt = native.extern
  def uv_fs_event_stop(handle: native.Ptr[uv_fs_event_t]): native.CInt = native.extern
  def uv_fs_event_getpath(handle: native.Ptr[uv_fs_event_t], buffer: native.Ptr[native.CChar], size: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_ip4_addr(ip: native.Ptr[native.CChar], port: native.CInt, addr: native.Ptr[struct_sockaddr_in]): native.CInt = native.extern
  def uv_ip6_addr(ip: native.Ptr[native.CChar], port: native.CInt, addr: native.Ptr[struct_sockaddr_in6]): native.CInt = native.extern
  def uv_ip4_name(src: native.Ptr[const_struct sockaddr_in], dst: native.Ptr[native.CChar], size: native.CInt): native.CInt = native.extern
  def uv_ip6_name(src: native.Ptr[const_struct sockaddr_in6], dst: native.Ptr[native.CChar], size: native.CInt): native.CInt = native.extern
  def uv_inet_ntop(af: native.CInt, src: native.Ptr[Byte], dst: native.Ptr[native.CChar], size: native.CInt): native.CInt = native.extern
  def uv_inet_pton(af: native.CInt, src: native.Ptr[native.CChar], dst: native.Ptr[Byte]): native.CInt = native.extern
  def uv_exepath(buffer: native.Ptr[native.CChar], size: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_cwd(buffer: native.Ptr[native.CChar], size: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_chdir(dir: native.Ptr[native.CChar]): native.CInt = native.extern
  def uv_get_free_memory(): native.CInt = native.extern
  def uv_get_total_memory(): native.CInt = native.extern
  def uv_hrtime(): native.CInt = native.extern
  def uv_disable_stdio_inheritance(): Unit = native.extern
  def uv_dlopen(filename: native.Ptr[native.CChar], lib: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_dlclose(lib: native.Ptr[native.CInt]): Unit = native.extern
  def uv_dlsym(lib: native.Ptr[native.CInt], name: native.Ptr[native.CChar], ptr: native.Ptr[native.Ptr[Byte]]): native.CInt = native.extern
  def uv_dlerror(lib: native.Ptr[native.CInt]): native.Ptr[native.CChar] = native.extern
  def uv_mutex_init(handle: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_mutex_destroy(handle: native.Ptr[native.CInt]): Unit = native.extern
  def uv_mutex_lock(handle: native.Ptr[native.CInt]): Unit = native.extern
  def uv_mutex_trylock(handle: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_mutex_unlock(handle: native.Ptr[native.CInt]): Unit = native.extern
  def uv_rwlock_init(rwlock: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_rwlock_destroy(rwlock: native.Ptr[native.CInt]): Unit = native.extern
  def uv_rwlock_rdlock(rwlock: native.Ptr[native.CInt]): Unit = native.extern
  def uv_rwlock_tryrdlock(rwlock: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_rwlock_rdunlock(rwlock: native.Ptr[native.CInt]): Unit = native.extern
  def uv_rwlock_wrlock(rwlock: native.Ptr[native.CInt]): Unit = native.extern
  def uv_rwlock_trywrlock(rwlock: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_rwlock_wrunlock(rwlock: native.Ptr[native.CInt]): Unit = native.extern
  def uv_sem_init(sem: native.Ptr[native.CInt], value: native.CUnsignedInt): native.CInt = native.extern
  def uv_sem_destroy(sem: native.Ptr[native.CInt]): Unit = native.extern
  def uv_sem_post(sem: native.Ptr[native.CInt]): Unit = native.extern
  def uv_sem_wait(sem: native.Ptr[native.CInt]): Unit = native.extern
  def uv_sem_trywait(sem: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_cond_init(cond: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_cond_destroy(cond: native.Ptr[native.CInt]): Unit = native.extern
  def uv_cond_signal(cond: native.Ptr[native.CInt]): Unit = native.extern
  def uv_cond_broadcast(cond: native.Ptr[native.CInt]): Unit = native.extern
  def uv_barrier_init(barrier: native.Ptr[native.CInt], count: native.CUnsignedInt): native.CInt = native.extern
  def uv_barrier_destroy(barrier: native.Ptr[native.CInt]): Unit = native.extern
  def uv_barrier_wait(barrier: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_cond_wait(cond: native.Ptr[native.CInt], mutex: native.Ptr[native.CInt]): Unit = native.extern
  def uv_cond_timedwait(cond: native.Ptr[native.CInt], mutex: native.Ptr[native.CInt], timeout: native.CInt): native.CInt = native.extern
  def uv_once(guard: native.Ptr[native.CInt], callback: native.CFunctionPtr0[Unit]): Unit = native.extern
  def uv_key_create(key: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_key_delete(key: native.Ptr[native.CInt]): Unit = native.extern
  def uv_key_get(key: native.Ptr[native.CInt]): native.Ptr[Byte] = native.extern
  def uv_key_set(key: native.Ptr[native.CInt], value: native.Ptr[Byte]): Unit = native.extern
  type uv_thread_cb = native.CFunctionPtr1[Unit,native.Ptr[Byte]]
  def uv_thread_create(tid: native.Ptr[native.CInt], entry: native.CFunctionPtr1[Unit,native.Ptr[Byte]], arg: native.Ptr[Byte]): native.CInt = native.extern
  def uv_thread_self(): native.CInt = native.extern
  def uv_thread_join(tid: native.Ptr[native.CInt]): native.CInt = native.extern
  def uv_thread_equal(t1: native.Ptr[native.CInt], t2: native.Ptr[native.CInt]): native.CInt = native.extern
  type union_uv_any_handle = native.CArray[native.Byte, 8]
  type union_uv_any_req = native.CArray[native.Byte, 8]
  type struct_uv_loop_s = native.CStruct6[native.Ptr[Byte],native.CUnsignedInt,void *[2],void *[2],native.CUnsignedInt,native.CInt]
}

object Hello extends App {
  val time = native.stackalloc[native.CDouble]
  val result = uv.uptime(time)
  //println("time: " + time + " result: " + result)
  println("Return " + result + " uptime: " + !time)
}